# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\"2\n\x0fRegisterRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"#\n\x10RegisterResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"/\n\x0cLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"6\n\rLoginResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x02 \x01(\t2\x86\x01\n\x0b\x41uthService\x12?\n\x0cRegisterUser\x12\x15.auth.RegisterRequest\x1a\x16.auth.RegisterResponse\"\x00\x12\x36\n\tLoginUser\x12\x12.auth.LoginRequest\x1a\x13.auth.LoginResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_REGISTERREQUEST']._serialized_start=20
  _globals['_REGISTERREQUEST']._serialized_end=70
  _globals['_REGISTERRESPONSE']._serialized_start=72
  _globals['_REGISTERRESPONSE']._serialized_end=107
  _globals['_LOGINREQUEST']._serialized_start=109
  _globals['_LOGINREQUEST']._serialized_end=156
  _globals['_LOGINRESPONSE']._serialized_start=158
  _globals['_LOGINRESPONSE']._serialized_end=212
  _globals['_AUTHSERVICE']._serialized_start=215
  _globals['_AUTHSERVICE']._serialized_end=349
# @@protoc_insertion_point(module_scope)
